### ISSUE TITLE
Now working on iOS5

### ISSUE THREAD

**Issue by Kastet** [rob-brown/RBFilePreviewer#2]
Just black screen...
Are you going to make it working on iOS5?

**Comment by rob-brown** [comment]
It's odd that `RBFilePreviewer` isn't working for iOS 5. It's a fairly thin wrapper around `QLPreviewController`. Does your file previewing code work on iOS 4.x? You may have your file paths set up wrong (they have to use the file scheme). Does `QLPreviewController` give you similar behavior? 

I haven't been able to use iOS 5 at all so far. I will definitely be making it iOS 5 compatible, but I don't know when I'll be able to get to it. If you know what's going wrong, then you can fork `RBFilePreviewer`, fix it, and send me a pull request. Otherwise, you'll have to wait until I (or someone else) get around to fixing it. 

Thanks for letting me know about this problem.

**Comment by Kastet** [comment]
It is working on 4.x, just compiled the same code on 5.0 beta. I did not try to use QLPreviewController on iOS5.

**Comment by rob-brown** [comment]
Everything appears to work on iOS 5.
